openapi: 3.0.0
info:
  description: Extracts Download API
  version: "1.0"
  title: Spring Boot REST API
  contact:
    name: GSA
    url: www.sam.gov
    email: reply@gsa.gov
  license:
    name: GSA
tags:
  - name: download-file-controller
    description: Download File Controller
paths:
  /extracts/v1/download:
    get:
      tags:
        - download-file-controller
      summary: Download an Extract File
      operationId: downloadUsingGET
      parameters:
        - name: api_key
          in: query
          description: Enter the Public API Key
          required: true
          schema:
            type: string
        - name: fileName
          in: query
          description: Extract Name from which extract file will download
          required: false
          schema:
            type: string
        - name: fileType
          in: query
          description: Domain of the File extract that will download
          required: false
          schema:
            type: string
        - name: sensitivity
          in: query
          description: >-
            Specifies desired sensitivity level of the extract that they wish to
            download
          required: false
          schema:
            type: string
        - name: frequency
          in: query
          description: >-
            Specifies desired Frequecy level of the extract that they wish to
            download
          required: false
          schema:
            type: string
        - name: charset
          in: query
          description: Specifies desired Char Set of the extract that they wish to download
          required: false
          schema:
            type: string
        - name: date
          in: query
          description: Specific date of the file that they wish to download
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Specific version of the file that they wish to download
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - download-file-controller
      summary: Download an Extract File
      operationId: downloadUsingPOST
      parameters:
        - name: api_key
          in: query
          description: Enter the Public API Key
          required: true
          schema:
            type: string
        - name: fileName
          in: query
          description: Extract Name from which extract file will download
          required: false
          schema:
            type: string
        - name: fileType
          in: query
          description: Domain of the File extract that will download
          required: false
          schema:
            type: string
        - name: sensitivity
          in: query
          description: >-
            Specifies desired sensitivity level of the extract that they wish to
            download
          required: false
          schema:
            type: string
        - name: frequency
          in: query
          description: >-
            Specifies desired Frequecy level of the extract that they wish to
            download
          required: false
          schema:
            type: string
        - name: charset
          in: query
          description: Specifies desired Char Set of the extract that they wish to download
          required: false
          schema:
            type: string
        - name: date
          in: query
          description: Specific date of the file that they wish to download
          required: false
          schema:
            type: string
        - name: version
          in: query
          description: Specific version of the file that they wish to download
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
servers:
  - url: //api-alpha.sam.gov/