openapi: 3.0.0
info:
  title: Search.gov Type-Ahead Search Suggestions API
  description: >-
    Search.gov is a service of the General Services Administration, providing search engine capability to federal agencies for their public websites. This API is specific to Search.gov and exposes the type-ahead suggestions that can appear below your search box as searchers enter their search terms.
  version: "2.0"
paths:
  /suggestions/:
    get:
      summary: Type-Ahead Search Suggestions
      parameters:
        - name: name
          in: query
          description: 'The value for the `name` parameter is your site handle on the Settings page.'
          required: true
          schema:
            type: string
            format: string
        - name: q
          in: query
          description: 'The characters entered by the users in the search box send a new call for each additional keystroke.'
          required: true
          schema:
            type: string
            format: string
        
      tags:
        - search
      
      responses:
        '200':
            description: You will see an array of suggestions. Suggestions are derived from the searches performed on your website. Up to five suggestions related to your visitors' search term are returned and are updated in near real time. A given term/phrase must be searched 10 times in a 24 hour period to appear as a suggestion.
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      
security: 
  - ApiKeyAuth: []
                
servers:
  - url: 'https://api.gsa.gov/technology/searchgov/v1'